### PR TITLE
Databases week1

### PR DESCRIPTION
**Pull request by negaren**

### CODE REVIEW

**Comment by martamatos** [comment]
I'm sorry Negar, but i can't even find your homework in this PR.
Can you do the PR from scratch please (save your homework files somewhere else, delete the homework branch both on your computer and github, and start again) ? 

And in the future do "git status" before "git commit" so that you don't commit files that don't belong in that commit ;p

**Comment by negaren** [comment]
Hi Marta

This is my homework link
<https://github.com/negaren/hyf-homework/pull/13/commits/b54856694a43012f759d510db355aa68ea609e62>
.
I tried to open in an incognito page and it was there.

Best Regards,
Negar

**Comment by martamatos** [comment]
Can i ask you to push a file with the homework only? I'm guessing your homework is in `databases/week1/classwork/hyf_lesson1_queries.sql`, but that file also has the class queries and i'm not sure what is what :/

**Comment by negaren** [comment]
creating a new branch from scatch

**Pull request closed without merging**
